import { Geist, Geist_Mono, Noto_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["devanagari", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin", "devanagari"],
});

export const metadata = {
  title: "LAS | The Sahara",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-auto" data-theme="light">
      <body className={`${geistSans.variable} ${poppins.variable} ${notoSans.variable} antialiased min-h-screen flex flex-col`}>
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
